import {defaults,endpoint,generateImage} from './api.js';
const $=id=>document.getElementById(id);
let config={...defaults}, key='', refs=[], batches=[], selected='', active=null, submitting=false, directory=null, previewItem=null, db=null;
const urls=new Map();
const states={queued:'等待生成',running:'正在生成',done:'已完成',error:'生成失败',stopped:'已停止'};
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;$('toasts').append(el);setTimeout(()=>el.remove(),6500);}
function element(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;}
function urlFor(blob){if(!urls.has(blob))urls.set(blob,URL.createObjectURL(blob));return urls.get(blob);}
function readConfig(){try{config={...defaults,...JSON.parse(localStorage.getItem('shiguang.config')||'{}')};}catch{config={...defaults};}for(const k of Object.keys(defaults)){if($(k))$(k).value=k==='extra'?JSON.stringify(config[k],null,2):config[k];}$('modelLabel').textContent=config.model;}
function settingsConfig(){const result={};for(const k of Object.keys(defaults))result[k]=$(k).value.trim();result.timeout=Number(result.timeout);result.pollSeconds=Number(result.pollSeconds);result.extra=JSON.parse(result.extra||'{}');if(!result.extra||Array.isArray(result.extra)||typeof result.extra!=='object')throw new Error('额外参数必须是 JSON 对象。');for(const p of [result.generationPath,result.editPath,result.taskPath])endpoint(result,p);return result;}
function openSettings(){$('apiKey').value=key;$('settings').showModal();}
$('settingsOpen').onclick=openSettings;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('settingsForm').onsubmit=e=>{e.preventDefault();try{config=settingsConfig();key=$('apiKey').value.trim();localStorage.setItem('shiguang.config',JSON.stringify(config));$('modelLabel').textContent=config.model;$('settingsOpen').classList.toggle('connected',Boolean(key));$('settings').close();toast('设置已保存');}catch(e){toast(e.message);}};
$('testConnection').onclick=async()=>{try{const c=settingsConfig();$('connectionResult').textContent='正在检查浏览器跨域访问…';const r=await fetch(endpoint(c,c.generationPath),{method:'POST',credentials:'omit',headers:{Authorization:'Bearer cors-check-invalid-key','Content-Type':'application/json'},body:JSON.stringify({model:c.model,prompt:'connection-check'}),signal:AbortSignal.timeout(15000)});$('connectionResult').textContent=r.status===401||r.status===403?`跨域可访问（HTTP ${r.status}）。未使用真实密钥，不验证余额或模型。`:`接口响应 HTTP ${r.status}。此检查不验证模型和余额。`;}catch(e){$('connectionResult').textContent='浏览器无法读取响应，请检查网络或服务商跨域配置。';}};
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('shiguang-studio',1);req.onupgradeneeded=()=>req.result.createObjectStore('batches',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function storeBatch(batch){if(!db)return;try{await new Promise((resolve,reject)=>{const tx=db.transaction('batches','readwrite');tx.objectStore('batches').put(batch);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}catch{toast('浏览器存储空间不足，请立即下载图片；当前页面仍可使用。');}}
async function loadBatches(){db=await openDB();batches=await new Promise((resolve,reject)=>{const req=db.transaction('batches').objectStore('batches').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});batches.sort((a,b)=>b.created-a.created);for(const batch of batches){for(const item of batch.items)if(['queued','running'].includes(item.status)){item.status='stopped';item.error='页面已关闭或刷新；服务端可能仍在生成，确认后可手动重试。';}}}
function renderRefs(){$('references').replaceChildren();refs.forEach((ref,i)=>{const card=element('div','reference');const img=element('img');img.src=urlFor(ref.blob);img.alt=`参考图 ${i+1}：${ref.name}`;img.onclick=()=>showPreview({blob:ref.blob,name:ref.name});card.append(img,element('span','index',i+1));const del=element('button','', '×');del.type='button';del.title='删除参考图片';del.onclick=()=>{refs.splice(i,1);renderRefs();};const role=element('select');role.setAttribute('aria-label',`参考图 ${i+1} 的角色`);for(const [v,t]of [['free','自由参考'],['subject','主体外观'],['background','背景'],['style','风格']]){const opt=element('option','',t);opt.value=v;role.append(opt);}role.value=ref.role;role.onchange=()=>{if(role.value==='background')for(const r of refs)if(r!==ref&&r.role==='background')r.role='free';ref.role=role.value;renderRefs();};card.append(del,role);$('references').append(card);});$('mode').textContent=refs.length?'图生图 · '+refs.length+' 张':'文生图';$('refHint').hidden=!refs.length;}
async function addFiles(files){for(const f of files){if(!['image/png','image/jpeg','image/webp'].includes(f.type)){toast('支持 PNG、JPG 和 WebP 图片');continue;}if(refs.length>=16){toast('本页面每次最多添加 16 张参考图');break;}if(f.size>30*1024*1024){toast('单张参考图片请控制在 30 MB 内');continue;}try{const bmp=await createImageBitmap(f);bmp.close();refs.push({name:f.name||'pasted.png',blob:f,role:'free'});}catch{toast('这张图片无法读取');}}renderRefs();}
$('fileInput').onchange=async e=>{await addFiles([...e.target.files]);e.target.value='';};
$('dropzone').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('fileInput').click();}};
for(const type of ['dragover','dragenter'])$('dropzone').addEventListener(type,e=>{e.preventDefault();$('dropzone').classList.add('dragover');});
$('dropzone').ondragleave=()=>$('dropzone').classList.remove('dragover');
$('dropzone').ondrop=e=>{e.preventDefault();$('dropzone').classList.remove('dragover');addFiles([...e.dataTransfer.files]);};
document.addEventListener('paste',e=>{if($('settings').open)return;const files=[...(e.clipboardData?.files||[])];if(files.length){e.preventDefault();addFiles(files);}});
document.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();});document.addEventListener('drop',e=>{if(e.dataTransfer.files.length)e.preventDefault();});
function updatePrompt(){$('promptCount').textContent=$('prompt').value.length+' 字';}$('prompt').oninput=updatePrompt;
$('count').oninput=()=>$('countBadge').textContent=$('count').value+' 张';
$('ratios').onclick=e=>{const b=e.target.closest('[data-size]');if(b){$('size').value=b.dataset.size;markRatio();}};
function markRatio(){document.querySelectorAll('[data-size]').forEach(b=>{const selected=b.dataset.size===$('size').value;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});}$('size').oninput=markRatio;
document.querySelectorAll('[data-idea]').forEach(b=>b.onclick=()=>{$('prompt').value=b.dataset.idea;updatePrompt();$('prompt').focus();});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!$('settings').open&&!active){$('createForm').requestSubmit();}if($('preview').open){if(e.key==='ArrowLeft')movePreview(-1);if(e.key==='ArrowRight')movePreview(1);}});
function effectivePrompt(prompt,inputs){const notes=[];inputs.forEach((ref,i)=>{if(ref.role==='background')notes.push(`第 ${i+1} 张为唯一背景参考，保持房间、家具布局、透视和光线；其他图片的背景不要混入。`);if(ref.role==='subject')notes.push(`第 ${i+1} 张仅用于主体外观与身份细节参考。`);if(ref.role==='style')notes.push(`第 ${i+1} 张仅用于风格参考。`);});return prompt+(notes.length?'\n\n参考图片分工：\n'+notes.join('\n'):'');}
$('createForm').onsubmit=async e=>{e.preventDefault();if(active||submitting)return;if(!key){toast('先填写 API Key，就可以开始创作');openSettings();return;}const prompt=$('prompt').value.trim();if(!prompt)return;submitting=true;$('generate').disabled=true;const count=Number($('count').value);const batch={id:crypto.randomUUID(),created:Date.now(),prompt,refs:refs.map(r=>({...r})),config:structuredClone(config),size:$('size').value.trim(),quality:$('quality').value,concurrency:Number($('concurrency').value),items:Array.from({length:count},(_,i)=>({id:crypto.randomUUID(),number:i+1,status:'queued'}))};batch.effectivePrompt=effectivePrompt(prompt,batch.refs);batches.unshift(batch);selected=batch.id;await storeBatch(batch);submitting=false;runBatch(batch);};
async function runBatch(batch,onlyIds=null){if(active)return;const controller=new AbortController();active={batch,controller};const runKey=key;const queue=batch.items.filter(i=>onlyIds?onlyIds.includes(i.id):i.status==='queued');queue.forEach(i=>{i.status='queued';i.error='';});render();let cursor=0;const worker=async()=>{while(cursor<queue.length&&!controller.signal.aborted){const item=queue[cursor++];item.status='running';await storeBatch(batch);renderGallery();try{const result=await generateImage({config:batch.config,key:runKey,prompt:batch.effectivePrompt,refs:batch.refs,size:batch.size,quality:batch.quality,signal:controller.signal,onStatus:s=>{item.label=s;renderGallery();}});Object.assign(item,result,{status:'done',name:`shiguang_${new Date(batch.created).toISOString().replace(/[:.]/g,'-')}_${String(item.number).padStart(2,'0')}.${result.blob.type==='image/jpeg'?'jpg':result.blob.type==='image/webp'?'webp':'png'}`});if(directory)await saveToDirectory(item).catch(e=>toast(e.message));}catch(e){item.status=controller.signal.aborted?'stopped':'error';item.error=String(e.message).split(runKey).join('[hidden]');}await storeBatch(batch);renderGallery();}};await Promise.all(Array.from({length:Math.min(batch.concurrency,queue.length)},worker));for(const i of queue)if(i.status==='queued')i.status='stopped';active=null;await storeBatch(batch);render();const good=batch.items.filter(i=>i.status==='done').length;toast(`本组已完成 ${good}/${batch.items.length} 张`);}
$('stop').onclick=()=>{if(active){active.controller.abort();toast('已停止等待和后续提交；已提交任务可能仍在服务端生成并计费。');}};
function currentBatch(){return batches.find(b=>b.id===selected);}
function visibleItems(){return (selected?batches.filter(b=>b.id===selected):batches).flatMap(b=>b.items.map(i=>({batch:b,item:i})));}
function render(){const previous=selected;$('batchSelect').replaceChildren();const all=element('option','','所有创作');all.value='';$('batchSelect').append(all);for(const b of batches){const opt=element('option','',`${new Date(b.created).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} · ${b.prompt.slice(0,18)} · ${b.items.length} 张`);opt.value=b.id;$('batchSelect').append(opt);}$('batchSelect').value=previous;$('generate').disabled=Boolean(active||submitting);$('stop').hidden=!active;$('reuse').disabled=!currentBatch();$('total').textContent=batches.reduce((n,b)=>n+b.items.filter(i=>i.status==='done').length,0);renderGallery();}
function renderGallery(){const entries=visibleItems();$('empty').hidden=Boolean(entries.length);$('gallery').replaceChildren();$('exportAll').disabled=!entries.some(e=>e.item.blob);for(const {batch,item}of entries){const card=element('article','image-card');const wrap=element('div','image-wrap');wrap.append(element('span','number',String(item.number).padStart(2,'0')));if(item.blob){const img=element('img');img.src=urlFor(item.blob);img.alt=`生成结果 ${item.number}`;img.loading='lazy';img.draggable=true;img.onclick=()=>showPreview(item);img.ondragstart=e=>{e.dataTransfer.setData('DownloadURL',`${item.blob.type}:${item.name}:${urlFor(item.blob)}`);e.dataTransfer.setData('text/uri-list',urlFor(item.blob));};wrap.append(img);}else{const content=element('div','pending-content');if(item.status==='running')content.append(element('div','spinner'));content.append(element('div','',item.label&&item.status==='running'?item.label:states[item.status]));if(item.error)content.append(element('p','helper',item.error));wrap.append(content);}const bottom=element('div','card-bottom');bottom.append(element('span','',item.blob?`${item.width} × ${item.height}`:batch.config.model));const buttons=element('div');if(item.blob){for(const [text,action]of [['放大',()=>showPreview(item)],['复制',()=>copyImage(item)],['下载',()=>download(item)]]){const b=element('button','',text);b.onclick=action;buttons.append(b);}}else if(['error','stopped'].includes(item.status)){const b=element('button','','重试此张');b.disabled=Boolean(active);b.onclick=()=>{if(!key){openSettings();return;}runBatch(batch,[item.id]);};buttons.append(b);}bottom.append(buttons);card.append(wrap,bottom);$('gallery').append(card);}}
$('batchSelect').onchange=e=>{selected=e.target.value;render();};
$('reuse').onclick=()=>{const b=currentBatch();if(!b)return;$('prompt').value=b.prompt;refs=b.refs.map(r=>({...r}));$('size').value=b.size;$('quality').value=b.quality;$('count').value=b.items.length;$('concurrency').value=b.concurrency;config=structuredClone(b.config);for(const k of Object.keys(defaults))$(k).value=k==='extra'?JSON.stringify(config[k],null,2):config[k];$('modelLabel').textContent=config.model;updatePrompt();renderRefs();markRatio();$('count').oninput();window.scrollTo({top:0,behavior:'smooth'});toast('已复用本组提示词、参考图及参数');};
function showPreview(item){previewItem=item;$('previewImage').src=urlFor(item.blob);$('previewTitle').textContent=item.name||`生成结果 ${item.number}`;if(!$('preview').open)$('preview').showModal();}
function movePreview(direction){const list=visibleItems().map(e=>e.item).filter(i=>i.blob);if(!list.length)return;const idx=list.indexOf(previewItem);showPreview(list[(idx+direction+list.length)%list.length]);}
$('prevImage').onclick=()=>movePreview(-1);$('nextImage').onclick=()=>movePreview(1);
function download(item){const a=element('a');a.href=urlFor(item.blob);a.download=item.name||'shiguang.png';document.body.append(a);a.click();a.remove();}
async function asPNG(blob){if(blob.type==='image/png')return blob;const image=await createImageBitmap(blob);const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;canvas.getContext('2d').drawImage(image,0,0);image.close();return new Promise(resolve=>canvas.toBlob(resolve,'image/png'));}
async function copyImage(item){try{if(!navigator.clipboard?.write||!window.ClipboardItem)throw new Error();await navigator.clipboard.write([new ClipboardItem({'image/png':asPNG(item.blob)})]);toast('图片已复制，可以粘贴到微信');}catch{toast('当前浏览器无法复制图片，请下载后发送。');}}
$('previewDownload').onclick=()=>download(previewItem);$('previewCopy').onclick=()=>copyImage(previewItem);
$('previewShare').onclick=async()=>{const file=new File([previewItem.blob],previewItem.name||'shiguang.png',{type:previewItem.blob.type});if(!navigator.canShare?.({files:[file]})){toast('当前浏览器不支持图片分享，请使用复制或下载');return;}try{await navigator.share({files:[file]});}catch(e){if(e.name!=='AbortError')toast('分享失败，请使用下载');}};
$('previewUse').onclick=()=>{addFiles([new File([previewItem.blob],previewItem.name||'reference.png',{type:previewItem.blob.type})]);$('preview').close();window.scrollTo({top:0,behavior:'smooth'});};
$('pickDir').onclick=async()=>{if(!window.showDirectoryPicker){toast('此浏览器不支持选择目录，请使用下载按钮；电脑端推荐 Chrome 或 Edge。');return;}try{directory=await window.showDirectoryPicker({mode:'readwrite'});$('saveDirInfo').hidden=false;$('saveDirInfo').textContent=`保存目录：${directory.name} · 后续生成图片自动保存到这里`;$('exportAll').textContent='保存本组';toast('已选择目录，后续图片会自动保存');}catch(e){if(e.name!=='AbortError')toast('无法访问此目录，请选择其他文件夹');}};
async function saveToDirectory(item){try{const handle=await directory.getFileHandle(item.name,{create:true});const w=await handle.createWritable();await w.write(item.blob);await w.close();}catch{throw new Error('图片已生成，但目录写入失败，请用下载按钮保存。');}}
$('exportAll').onclick=async()=>{const items=visibleItems().map(e=>e.item).filter(i=>i.blob);if(!items.length)return;if(directory){for(const i of items)try{await saveToDirectory(i);}catch(e){toast(e.message);return;}toast(`已保存 ${items.length} 张到 ${directory.name}`);}else{for(const i of items){download(i);await new Promise(r=>setTimeout(r,250));}toast('已请求下载。若未全部下载，请允许此网站下载多个文件。');}};
window.addEventListener('beforeunload',e=>{if(active){e.preventDefault();e.returnValue='';}});
readConfig();try{await loadBatches();}catch{toast('当前浏览器无法保存历史，建议下载生成结果。');}render();
